blank_issues_enabled: false
contact_links:
    - name: 💬 Diskusi & Tanya Jawab
      url: https://github.com/iamgdevvv/iamgdevvv/pulls
      about: Untuk pertanyaan umum, ide, atau diskusi yang bukan bug/fitur.
    - name: 🙌 Panduan Kontribusi
      url: https://github.com/iamgdevvv/iamgdevvv/blob/site-v2/CONTRIBUTING.md
      about: Pelajari cara berkontribusi ke proyek ini.
